
# DELETE     http://localhost:5555/books/65ad564e3c972abe5b10067c
# Content-Type: application/json

GET    http://localhost:5555/books
Content-Type: application/json

# DELETE  http://localhost:5555/delete/65ab52239c38f45f8201fcac
# Content-Type: application/json

# PUT    http://localhost:5555/create/65ab52239c38f45f8201fcac
# Content-Type: application/json

# PUT   http://localhost:5555/books/65ad5f12de7371a338d1b0c7
# Content-Type: application/json

# {
#     "title": "Hey?",
#     "author": "Hassan",
#      "year": 2027
# } 

